_target_: src.datasets.hmnist_gpvae_imputed.HealingMNISTImputedGPVAE

x_path: ${paths.data_dir}/HMNIST/hmnist_imputed.pt
y_path: data/HMNIST/hmnist_imputed_labels.pt
batch_size: 64
num_workers: 4
test_split: 5000
is_test_only: True