# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train_old.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: test_Accuracy

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: ucr

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 130

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 80 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:

      model.optimizer.lr: range(0.0001, 0.01, 0.00001)
      model.beta: range(0.0001, 0.01, 0.00001)
      model.optimizer.weight_decay: range(0.0001, 0.05, 0.00001)

      model.timeseries_encoder.n_cnn_layers: choice(1, 2, 3, 4)
      +n_encoder_layers: choice(0, 1, 2)
      +n_decoder_layers: choice(0, 1, 2)

      model.timeseries_encoder.encoding_series_length: choice(2, 8, 16, 64, 256, 400)
      model.num_samples: choice(1, 4, 8, 16)
      model.length_scale: range(0.5, 10, 0.1)

    custom_search_space: utils.optuna_hooks.ucr

is_ensemble: ${model.is_ensemble}