defaults:
  - _self_
  - datamodule: mimic3
  - model: mimic3/gpvib_e_cnn2d_d_flatten
  - trainer: gpu
  - logger: tensorboard
  - callbacks: default
  - hydra: default
  - debug:
  - paths: default
#  - hparams_search: hmnist/ss_gpvib_e_cnn1d_dl_flatten
  - metrics: vib_val
  - extras: default

seed:
mode: debug
run_test: False
optimized_metric: ${metrics.optimize}

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
ckpt_path: null # path to checkpoint model

# name of the run, should be used along with experiment mode
datamodule_name: mimic3
model_name: gpvib_e_cnn2d_d_flatten


