# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

# disable callbacks and loggers during debugging
#callbacks: null

extras:
  ignore_warnings: False
  enforce_tags: False

  # use this to also set hydra loggers to 'DEBUG'
  # verbose: True

trainer:
  max_epochs: 1
#  accelerator: cpu # debuggers don't like gpus
#  devices: 1 # debuggers don't like multiprocessing
#  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

datamodule:
  num_workers: 1 # debuggers don't like multiprocessing

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

  # sets level of all command line loggers to 'DEBUG'
  verbose: True

