_target_: src.models.basics.gpvib.GPVIB
_partial_: True

timeseries_encoder:
  _target_: src.models.encoders.BlockTimeSeriesDataEncoder
  _partial_: True
  input_size: -1
  ts_embedding_size: -1
  n_cnn_layers: -1
  out_channels_1: -1
  out_channels_2: -1
  out_channels_3: -1
  out_channels_4: -1
  kernel_size_1: -1
  kernel_size_2: -1
  kernel_size_3: -1
  kernel_size_4: -1
  dropout_1: -1
  dropout_2: -1
  dropout_3: -1
  dropout_4: -1
  time_series_hidden_1: 400
  time_series_hidden_2: -1
  time_series_hidden_3: -1
  hidden_size_1: -1
  hidden_size_2: -1
  hidden_size_3: -1
  timeseries_size: -1
  encoding_size: 8

encoder:
  _target_: src.models.encoders.BandedJointEncoder
  _partial_: True
  precision_activation:
    _target_: torch.nn.Softmax
  encoding_size: ${model.timeseries_encoder.encoding_size}

decoder:
  _target_: src.models.decoders.FlattenMultinomialDecoder
  _partial_: True
  z_dim: ${model.timeseries_encoder.encoding_size}
  hidden_size_1: 64
  hidden_size_2: -1
  hidden_size_3: -1
  num_samples: ${model.num_samples}
  output_size: ${model.num_classes}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.5
  patience: 50
  mode: ${callbacks.early_stopping.mode}
  threshold: 0.00001
  cooldown: 0
  min_lr: 1e-5

# vib
num_classes:
alpha: -1
beta: 0.01
num_samples: 16
class_weight_file:
monitor_metric: ${callbacks.early_stopping.monitor} # for the scheduler
use_class_weight: false
sample_during_evaluation: false

# time series vib
is_ensemble: False # always false

# gp_vib
kernel: cauchy
sigma: 2
length_scale: 2
kernel_scales: 1
